from __future__ import annotations

from typing import Any, Protocol


class CachePort(Protocol):
    async def get_metrics(self) -> dict[str, Any]: ...
    async def invalidate_tags(self, tags: list[str]) -> int: ...
    async def invalidate_where(self, probe: list[float], threshold: float) -> int: ...


class FabricPort(Protocol):
    async def broadcast_signal(self, payload: dict[str, Any]) -> None: ...
    async def peer_count(self) -> int: ...


class GuardPort(Protocol):
    async def caps(self, profile: str) -> dict[str, Any]: ...
    async def recent_logs(self, limit: int = 50) -> list[dict[str, Any]]: ...


class ShinePort(Protocol):
    async def capabilities(self) -> dict[str, Any]: ...


class CortexPort(Protocol):
    async def facts(self, tenant_id: str) -> list[dict[str, Any]]: ...
    async def conflicts(self, tenant_id: str) -> list[dict[str, Any]]: ...
    async def resolve_conflict(
        self, tenant_id: str, conflict_id: str, resolution: dict[str, Any]
    ) -> dict[str, Any]: ...
    def sleep(self, tenant_id: str) -> None: ...


class GraphPort(Protocol):
    async def dogfood(self) -> dict[str, Any]: ...
    async def mark_revalidate(self, tenant_id: str, tags: list[str]) -> None: ...


class RagPort(Protocol):
    async def tree(self, tenant_id: str) -> dict[str, Any]: ...
    async def search(self, tenant_id: str, query: str) -> list[dict[str, Any]]: ...
    async def partitions(self, tenant_id: str) -> list[dict[str, Any]]: ...
